import json

from runexe.compatibility import (
    analyze_compatibility,
    classify_application,
    detect_anti_cheat_warnings,
    detect_apphost_dotnet_version,
    dotnet_version_to_verb,
)
from runexe.models import ExecutableInfo, HostInfo, PEImport, VersionInfo
from runexe.profiles import PAINT_NET, detect_runtime_issue


def executable(tmp_path, imports=None, architecture="x86_64"):
    path = tmp_path / "app.exe"
    path.touch()
    return ExecutableInfo(
        path=path,
        valid=True,
        architecture=architecture,
        subsystem="Windows GUI",
        imports=imports or [],
        data_directories=[],
    )


def test_single_generic_graphics_import_is_not_enough_to_call_app_a_game(tmp_path):
    app = executable(tmp_path, [PEImport("d3d11.dll")])

    result = classify_application(app)

    assert result.category == "application"
    assert result.confidence == "medium"
    assert result.signals == []


def test_steam_api_import_is_a_high_confidence_standalone_signal(tmp_path):
    app = executable(tmp_path, [PEImport("steam_api64.dll")])

    result = classify_application(app)

    assert result.category == "game"
    assert result.confidence == "high"
    assert "steam_api64.dll" in result.signals[0]


def test_epic_online_services_import_is_a_standalone_signal(tmp_path):
    app = executable(tmp_path, [PEImport("EOSSDK-Win64-Shipping.dll")])

    result = classify_application(app)

    assert result.category == "game"
    assert result.confidence == "high"
    assert "Epic Online Services" in result.signals[0]


def test_gog_galaxy_import_is_a_standalone_signal(tmp_path):
    app = executable(tmp_path, [PEImport("Galaxy64.dll")])

    result = classify_application(app)

    assert result.category == "game"
    assert "GOG Galaxy" in result.signals[0]


def test_combined_weak_signals_are_only_medium_confidence(tmp_path):
    app = executable(tmp_path, [PEImport("d3d11.dll"), PEImport("xinput1_3.dll")])

    result = classify_application(app)

    assert result.category == "game"
    assert result.confidence == "medium"


def test_unityplayer_import_is_a_high_confidence_standalone_signal(tmp_path):
    app = executable(tmp_path, [PEImport("UnityPlayer.dll")])

    result = classify_application(app)

    assert result.category == "game"
    assert result.confidence == "high"
    assert "Unity" in result.signals[0]


def test_unreal_engine_name_in_version_info_is_detected_without_any_import(tmp_path):
    app = executable(tmp_path, imports=[])
    app.version_info = VersionInfo(strings={"ProductName": "MyGame (Unreal Engine)"})

    result = classify_application(app)

    assert result.category == "game"
    assert result.confidence == "high"
    assert "Unreal Engine" in result.signals[0]


def test_godot_engine_name_in_file_description_is_detected(tmp_path):
    app = executable(tmp_path, imports=[])
    app.version_info = VersionInfo(strings={"FileDescription": "Generated by Godot Engine"})

    result = classify_application(app)

    assert result.category == "game"
    assert "Godot Engine" in result.signals[0]


def test_unity_data_directory_is_detected_with_no_import_or_metadata(tmp_path):
    app = executable(tmp_path, imports=[])
    (app.path.parent / "app_Data").mkdir()

    result = classify_application(app)

    assert result.category == "game"
    assert result.confidence == "high"
    assert "Unity" in result.signals[0]


def test_unreal_engine_content_directories_are_detected(tmp_path):
    app = executable(tmp_path, imports=[])
    (app.path.parent / "Engine").mkdir()
    (app.path.parent / "Content").mkdir()

    result = classify_application(app)

    assert result.category == "game"
    assert "Unreal Engine" in result.signals[0]


def test_gamemaker_data_win_is_detected(tmp_path):
    app = executable(tmp_path, imports=[])
    (app.path.parent / "data.win").touch()

    result = classify_application(app)

    assert result.category == "game"
    assert "GameMaker" in result.signals[0]


def test_godot_pck_file_is_detected(tmp_path):
    app = executable(tmp_path, imports=[])
    (app.path.parent / "app.pck").touch()

    result = classify_application(app)

    assert result.category == "game"
    assert "Godot Engine" in result.signals[0]


def test_a_lone_content_directory_is_not_enough_to_call_it_unreal(tmp_path):
    # "Content" alone is too generic a folder name to use as a signal on
    # its own -- only the Engine+Content pair together is Unreal-specific.
    app = executable(tmp_path, imports=[])
    (app.path.parent / "Content").mkdir()

    result = classify_application(app)

    assert result.category == "application"


def test_game_uses_available_wine_backend_and_recommends_proton(tmp_path):
    app = executable(tmp_path, [PEImport("d3d11.dll"), PEImport("xinput1_3.dll")])
    host = HostInfo(
        "x86_64",
        True,
        "wine-10",
        True,
        True,
        True,
        proton_installed=True,
        proton_versions=["Proton Experimental"],
    )

    report = analyze_compatibility(app, host)

    assert report.category == "game"
    assert report.backend == "proton"
    assert report.recommended_runtime == "Proton Experimental"


def test_direct3d_reports_vulkan_problem_without_blocking_wined3d_fallback(tmp_path):
    app = executable(tmp_path, [PEImport("d3d11.dll")])
    host = HostInfo("x86_64", True, "wine-11", True, True, True, vulkan_available=False)

    report = analyze_compatibility(app, host)

    assert report.graphics is not None
    assert report.graphics.translators == ("DXVK",)
    assert any("WineD3D" in warning for warning in report.warnings)


def test_warns_when_direct3d_app_has_no_hardware_vulkan_driver(tmp_path):
    app = executable(tmp_path, [PEImport("d3d11.dll")])
    host = HostInfo("x86_64", True, "wine-10", True, True, True, vulkan_supported=False)

    report = analyze_compatibility(app, host)

    assert any("Vulkan" in warning for warning in report.warnings)


def test_no_vulkan_warning_when_hardware_driver_is_present(tmp_path):
    app = executable(tmp_path, [PEImport("d3d11.dll")])
    host = HostInfo(
        "x86_64",
        True,
        "wine-10",
        True,
        True,
        True,
        vulkan_supported=True,
        gpu_vendors=["amd"],
    )

    report = analyze_compatibility(app, host)

    assert not any("Vulkan" in warning for warning in report.warnings)


def test_no_vulkan_warning_for_apps_without_direct3d_on_wine_backend(tmp_path):
    app = executable(tmp_path, [])
    host = HostInfo("x86_64", True, "wine-10", True, True, True, vulkan_supported=False)

    report = analyze_compatibility(app, host)

    assert not any("Vulkan" in warning for warning in report.warnings)


def test_proton_backend_always_warns_without_vulkan_even_without_d3d_import(tmp_path):
    app = executable(tmp_path, [PEImport("steam_api64.dll")])
    host = HostInfo(
        "x86_64",
        True,
        "wine-10",
        True,
        True,
        True,
        proton_installed=True,
        proton_versions=["Proton Experimental"],
        vulkan_supported=False,
    )

    report = analyze_compatibility(app, host)

    assert report.backend == "proton"
    assert any("Vulkan" in warning for warning in report.warnings)


def test_report_surfaces_classification_confidence_and_signals(tmp_path):
    app = executable(tmp_path, [PEImport("steam_api64.dll")])

    report = analyze_compatibility(app)

    assert report.classification_confidence == "high"
    assert report.classification_signals
    assert any("Classified as game" in note for note in report.notes)


def test_anti_cheat_is_a_warning_not_a_hard_blocker(tmp_path):
    app = executable(tmp_path, [PEImport("EasyAntiCheat_x64.dll")])

    report = analyze_compatibility(app)

    assert detect_anti_cheat_warnings(app)
    assert report.warnings
    assert not report.blocking_issues


def test_x86_is_not_marked_unsupported_when_host_probe_is_inconclusive(tmp_path):
    app = executable(tmp_path, architecture="x86")
    host = HostInfo("x86_64", True, "wine-10", None, None, True)

    report = analyze_compatibility(app, host)

    assert report.supported
    assert report.wine_arch == "win64"


def test_reads_desktop_runtimeconfig(tmp_path):
    app = executable(tmp_path)
    app.path.with_name("app.runtimeconfig.json").write_text(
        json.dumps(
            {
                "runtimeOptions": {
                    "frameworks": [
                        {"name": "Microsoft.NETCore.App", "version": "8.0.1"},
                        {"name": "Microsoft.WindowsDesktop.App", "version": "8.0.1"},
                    ]
                }
            }
        ),
        encoding="utf-8",
    )

    assert detect_apphost_dotnet_version(app.path) == ("8.0.1", True)
    assert dotnet_version_to_verb("8.0.1", True) == "dotnetdesktop8"
    assert dotnet_version_to_verb("6.0.30", False) == "dotnet6"


def test_self_contained_dotnet_does_not_install_shared_runtime(tmp_path):
    app = executable(tmp_path)
    app.path.with_name("app.runtimeconfig.json").write_text(
        json.dumps(
            {
                "runtimeOptions": {
                    "includedFrameworks": [
                        {"name": "Microsoft.WindowsDesktop.App", "version": "8.0.1"}
                    ]
                }
            }
        ),
        encoding="utf-8",
    )

    report = analyze_compatibility(app)

    assert "dotnetdesktop8" not in report.required_verbs
    assert any("self-contained" in note for note in report.notes)


def test_rejects_non_object_runtimeconfig(tmp_path):
    app = executable(tmp_path)
    app.path.with_name("app.runtimeconfig.json").write_text("[]", encoding="utf-8")

    assert detect_apphost_dotnet_version(app.path) == (None, False)


def test_detects_paint_net_and_recommends_modern_windows(tmp_path):
    app = executable(tmp_path)
    app.path = app.path.with_name("PaintDotNet.exe")
    app.path.touch()

    report = analyze_compatibility(app)

    assert report.profile is not None
    assert report.profile.key == "paint-dot-net"
    assert report.profile.minimum_windows_build == 19044
    assert report.profile.recommended_windows_version == "11"
    assert any("21H2" in note for note in report.notes)


def test_recognizes_paint_net_old_windows_failure():
    diagnostic = detect_runtime_issue("", 1150 % 256, PAINT_NET)

    assert diagnostic is not None
    assert diagnostic.recommended_windows_version == "11"
    assert "rejected the Windows version" in diagnostic.message
